name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD) # gives the latest commits SHA
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t pranchal04/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true pranchal04/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: complex-k8s-366707
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-a
 
    # Here the SHA is the one associated with each commit to github and it is unique
      - name: Build
        run: |-
          docker build -t pranchal04/multi-client:latest -t pranchal04/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t pranchal04/multi-server:latest -t pranchal04/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t pranchal04/multi-worker:latest -t pranchal04/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push pranchal04/multi-client:latest
          docker push pranchal04/multi-server:latest
          docker push pranchal04/multi-worker:latest
 
          docker push pranchal04/multi-client:${{ env.SHA }}
          docker push pranchal04/multi-server:${{ env.SHA }}
          docker push pranchal04/multi-worker:${{ env.SHA }}
 
    # Imperative Command
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=pranchal04/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=pranchal04/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=pranchal04/multi-worker:${{ env.SHA }}